/**:
  ros__parameters:
    num_robots: 4   # working primarily with 4 robots
    publish_rate: 10.0   # in Hz, for contro loop timer
    max_acc: 0.8  # in m/s2

    # Acceleration control parameters for all robots
    k_p: 1.5    # consensus gain - (determines the speed of reaching consensus)
    k_d: 0.8    # damping factor - (to slow down velocity as robots reach consensus)
    k_separation: 3.0   # repulsive force
    safe_dist: 0.8    # minimum safe distance between robots (0.5)

    # mission params (for sake of simplicity)
    const_speed: 1.0  # using constant speed to keep time ~ distance to task
    spacing: 0.8  # desired spacing between robots in the chosen formation